README.md:
	touch README.md

README.md : guessinggame.sh
	echo "The title of the project is  \"Guessing Game\"" > README.md
	echo "" >> README.md
	wc -l guessinggame.sh | egrep -o "[0-9]+" >> README.md




